version: '3'
services:
  backend:
    image: il_manque_du_beurre_backend
    command: flask run --host='0.0.0.0'
    environment:
      DATABASE_PASSWORD: example
    ports:
    - "5000:5000"
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app

  database:
    image: il_manque_du_beurre_database
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
    restart: always
    volumes:
      - ./database:/app
      - ./database/pgdata:/var/lib/postgresql/data/pgdata
    working_dir: /app
