version: '3'
services:
  backend:
    image: il_manque_du_beurre_backend
    command: flask run --host='0.0.0.0'
    ports:
      - "5000:5000"
    environment:
      DATABASE_PASSWORD: example
    volumes:
      - ./backend:/app
    working_dir: /app

  database:
    image: il_manque_du_beurre_database
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/app
    working_dir: /app
