version: '3'
services:
  backend:
    image: il_manque_du_beurre_backend
    command: flask run --host='0.0.0.0'
    ports:
      - "5000:5000"
    environment:
      DATABASE_PASSWORD: example
    volumes:
      - .:/app
    working_dir: /app
  database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
