swagger: "2.0"

info:
  version: 1.0.1
  title: Il manque du beurre
  description: Une api pour signaler qu'il manque un produit à la maison

schemes:
  - http
host: ""
basePath: /api

paths:
  /produits_manquants:
    get:
      summary: Liste les produits manquants
      responses:
        '200':
          description: La liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nom:
                    type: string
                    example: 'beurre'

  /produits_manquants/{nom_de_produit}:
    parameters:
      - name: nom_de_produit
        in: path
        required: true
        description: Nom du produit manquant à signaler
        schema:
          type: string
    post:
      summary: Signale un produit manquant
      responses:
        '200':
          description: Ok, le produit manquant a été signalé
        '400':
          description: "Erreur : le produit demandé n'est pas connu"
          content:
            application/json:
              schema:
                type: object
                properties:
                  erreur:
                    type: object
                    properties:
                      description:
                      type: string
